### ISSUE TITLE
Failed to verify scanner and GMP Service is down

### ISSUE THREAD

**Issue by DavideFranchioni** [yu210148/gvm_install#10]
Hello,

At the end of the installation i noticed the error failed to verify scanner.
I waited 5m then i used the commands `gvmd --get-scanners` to get the list of the scanner, so i get the UUID.

I verified the scanner with the command:
`gvmd --verify-scanner=myUUID`
And it worked.

After that i run the UI, and if i try to login i get the error GMP Service is down.

Looking at services from the termina, the service gvm.service is down:
```
gvm@VA:~$ systemctl status gvm.service 
● gvm.service - Control the OpenVAS GVM service
     Loaded: loaded (/etc/systemd/system/gvm.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2020-09-04 09:44:20 CEST; 27min ago
TriggeredBy: ● gvm.path
    Process: 51074 ExecStart=/opt/gvm/sbin/gvmd --osp-vt-update=/opt/gvm/var/run/ospd.sock (co>
   Main PID: 51074 (code=exited, status=1/FAILURE)
gvm@VA:~$ systemctl start gvm.service 
```
I try to restart the service but still not working.

What can i verify in this case?

Thank you in advance.

**Comment by aretsmarvin** [comment]
Is it for all the scanners, or just one?
By default there are 3 scanners:
![image](https://user-images.githubusercontent.com/45003967/98702228-6efd2c00-237a-11eb-8635-e8fca2ff3fef.png)

The first 2 are working for me, the "OpenVAS Default"  isn't working. Maybe you have the same issue?

**Comment by yu210148** [comment]
Hi there,

The OpenVAS Default scanner doesn't work for me either. The author of the
walkthrough that I based the script on made another one and got that going.
The script creates the one called 'Created OpenVAS Scanner' which is the
one to select when creating a scan.

Hope that helps. :)

kev.

**Comment by yu210148** [comment]
I believe what's described is the same as Issue #9 so I'm going to close this off as a duplicate for now
