### ISSUE TITLE
Scans interrupted with error "Cannot connect to Scanner"

### ISSUE THREAD

**Issue by dustinbird** [yu210148/gvm_install#100]
I have a new issue that has happened on one of our scanner boxes that has been working without errors up until this (while I was away).
All the current scheduled scans (and when manually triggered) are failing with a status of interrupted.  When I look at the task the only error message I see is "Cannot connect to scanner" but no detailed log.

![image](https://github.com/yu210148/gvm_install/assets/68902707/c1ce67a9-5b19-47d8-a9bd-dc9a63c2fe28)

As mentioned this was working until Friday when I took annual leave but seems to have started with scans failing from Saturday onwards.  Last Thursday I updated the docker image to get the latest version and the same was run on another box the following day but this is unaffected.  I have today updated the docker image again, I have ran all available servers patches and rebooted the server (OpenSUSE Leap 15.5).

![image](https://github.com/yu210148/gvm_install/assets/68902707/407bb4cd-2813-44c9-aeea-067b8cd17937)

 When I look at the container log I see the following error:

`osp_scanner_feed_version: failed to connect to /var/run/ospd/ospd-openvas.sock\n","stream":"stdout","time":"2024-05-02T12:55:27.127335941Z"}`

this file does not exist on this server but nor does it on another scanning server set-up the same way running the same OpenSUSE build and GVM versions with no errors.

What can I do to correct this?

**Comment by yu210148** [comment]
Hi Dustin, 

I think this issue might be better filed with the https://github.com/itiligent/GVM-Install project. This installer script has been superseded by that one.
