### ISSUE TITLE
URL?

### ISSUE THREAD

**Issue by Bloodyfisted** [yu210148/gvm_install#18]
Pardon my noobish-ness here. I have a fresh install of Ubuntu 20.04 and i went ahead and ran this script... I've skimmed through all 300+ lines and I can't seem find the what the default URL is of the installation....

**Comment by yu210148** [comment]
Hi There,

No worries. It should be the IP address of the machine which can be found with the command:

`ip a`

so once done you should be able to access the interface at https://<ip-address-of-machine> 

I'm working on getting a version of this script that'll work on Debian too and have run into the GVM service is unavailable message that's been mentioned in some of the other issues. So you may see that. I'm not sure what the solution to that is although some have suggested waiting for it to resolve itself. I'm not sure how long that takes though.

I hope to have an updated version of this merged in the next few days.

kev.

**Comment by Bloodyfisted** [comment]
So it defaults to https://127.0.0.1:9392. I ended up running the script twice, only noticeable difference is that now I have 2 of the same scanner (created OpenVas Scanner), not sure if that's causing any issues. I cannot scan using OpenVas Default scanner, I immediately get a failed error. However, i'm doing a test scan with one of the "Created OpeVAS Scanner", that process seemed to at least be doing something.

**Comment by yu210148** [comment]
Yes, the default scanner doesn't work. That's the case too I found when I
followed the guide and did it all manually.

I don't know why it would be listening on that port but if it works for you
I'll take it. 🙂

Kev.
