### ISSUE TITLE
I believe what am asking is how to run the very first command of wget

### ISSUE THREAD

**Issue by elejefelinuxgeek** [yu210148/gvm_install#19]
![wget](https://user-images.githubusercontent.com/76115339/102373225-06384d80-3fd1-11eb-9461-7f947a2dad04.png)

Hello I dont understand this line "wget https://raw.githubusercontent.com/<account>/gvm_install/master/install_gvm.sh"  I am a newbie and very blunt, I am trying to run the script but when i use the above on the terminal it says "bash: account: No such file or directory" what am I supposed to do step by step please, imagine I dont know anything, please help me. I get confused with <account> I dont know what you mean there or what I should put there and wget is saving as index.html and when i open in the editor i am seeing different things not the script

**Comment by yu210148** [comment]
Oops. The line should read 
>`wget https://raw.githubusercontent.com/yu210148/gvm_install/master/install_gvm.sh`
I'm just testing some changes that I'm going to merge into the main branch. I'll update the README file when I do that.

Sorry for the confusion.

What that line does is download the script to your machine. The next makes it executable then the next actually runs the script. Once it finishes--if all goes well--you should be able to point a browser to the IP address of the machine you ran the script on and access the web interface. For example, if you ran it on a machine with the IP 192.168.0.5 the web interface would be accessible at https://192.168.0.5. 

kev.

**Comment by elejefelinuxgeek** [comment]
Hey Kev, I kinda figured that out, thanks for pointing me in the right direction as well, so am running the script and am sure it will take a while, will get back to you if anything else comes up, thanks alot

**Comment by elejefelinuxgeek** [comment]
hey Kevin the script worked and i had no problem with installation, the only problem was that after installation i opened up the web interface but could not login, I believe I have to wait as the script says at the end, i will revert to you once their is a change

**Comment by yu210148** [comment]
What message are you getting when you try to log in? I've been testing
while working on issue 17 and have run into the same thing where I can't
log on once it finishes. I haven't had a chance to let it be for more than
a few minutes so far so I don't know how long it might need.

Kev.

**Comment by elejefelinuxgeek** [comment]
![gvm](https://user-images.githubusercontent.com/76115339/102712181-1cdfec80-42d0-11eb-9368-4311707822dd.png)

THats the screenshot of what happens when i try to login, what do you think i should do to be able to log in

**Comment by yu210148** [comment]
Yes, that's what I was getting too. I'm not sure why it's doing that but it's been reported on Issue #9 and #10. Someone there has suggested waiting for the issue to resolve itself but I've not had the chance to see how long that might take--or even if it does sort itself out.

**Comment by yu210148** [comment]
Humm, went to look at this again this morning, and when I spun up the Ubuntu and Debian virtual machines I'd run the script on they both let me log in. I updated the feeds and ran a test scan with the 'Created OpenVAS Scanner' and it worked as expected on the Ubuntu VM. 

I'm still not sure what causes the GMP Service is down message to appear when the script finishes and one tries to log in but it does appear to resolve itself--although it may require restarting the machine.
