### ISSUE TITLE
A few minor fixes

### ISSUE THREAD

**Issue by kirk56k** [yu210148/gvm_install#2]
Going through this script now one line at a time. I found a few minor fixes I might recommend. I'll add them below and continue to edit this as I find them.

1) The "greenbone-certdata-sync" script has the same NAT issue as the "greenbone-scrapdata-sync" script does. However, your script does not add the necessary sleep command for it. You'll want to insert a "sleep 300" at line #349 on "greenbone-certdata-sync".

2) I think for the updates you'd be better off creating a small script with each of the four commands and sleep's in between each. While it's extremely unlikely to happen, it is possible with your script to end up with two of the download commands scheduled too close to one another.

**Comment by ankush-grover-3pg** [comment]
I faced an issue with the Reports that was all reports except XML were having 0 bytes. After long search I found a post which tells to install "apt-get install xsltproc texlive-latex-base texlive-latex-extra". xsltproc package was missing which was causing all reports having 0 bytes. I hope this will help others who are facing or might face the same issue.

**Comment by yu210148** [comment]
Thanks for the info, I've added xsltproc to the list of packages that the script installs (commit https://github.com/yu210148/gvm_install/commit/5d18787f398ce079be80a417d6b4156b60916e43
