### ISSUE TITLE
Don't create unnecessary "Created OpenVAS Scanner"

### ISSUE THREAD

**Issue by cfi-gb** [yu210148/gvm_install#23]
It seems that the script is currently creating a second OpenVAS Scanner called "Created OpenVAS Scanner" besides the "OpenVAS Default" one here:

https://github.com/yu210148/gvm_install/blob/master/install_gvm.sh#L380

This is currently not necessary and is also causing issues for users choosing the "OpenVAS Default" and not the "Created OpenVAS Scanner". Instead you could update the ospd socket path to the required location with something like e.g. (AFAIK the uuid of the "OpenVAS Default" is always the same):

```
gvmd --modify-scanner=08b69003-5fc2-4037-a479-93b440211c73 --scanner-host=/opt/gvm/var/run/ospd.sock
```

See:

https://github.com/greenbone/gvmd/blob/gvmd-20.08/INSTALL.md#configure-the-default-ospd-scanner-socket-path

**Comment by yu210148** [comment]
Hi, thanks, I'll look into having it do this. I originally was following the how-to referenced in the README which created the additional scanner but I agree, using the default one would be better.

kev.

**Comment by yu210148** [comment]
Thanks for this. I just merged it in. :)

kev.

**Comment by cfi-gb** [comment]
Cross-ref: #25

Changes looks good :+1:

**Comment by yu210148** [comment]
Thanks for taking a look at it.
