### ISSUE TITLE
redis-server config improvements for stuck scans

### ISSUE THREAD

**Issue by cfi-gb** [yu210148/gvm_install#24]
There are currently two known redis-server config improvements which could be incorporated into this script:

https://community.greenbone.net/t/hint-redis-setup-configuration-for-gse-gvm-openvas/333

Basically raising the `databases` setting and commenting out/remove all `save xy z` (e.g. `save 900 1`) in the redis.conf should make redis-server ready for GVM.

**Comment by yu210148** [comment]
Hi,

I believe this is already taken care of. Line 132 of the script creates the redis config for openvas with the save lines commented out. 

kev.

**Comment by cfi-gb** [comment]
Ah, indeed. Had missed that the script uses the https://github.com/greenbone/openvas/blob/master/config/redis-openvas.conf scan config which is already taking care of this. Thanks a lot :+1:

**Comment by yu210148** [comment]
Great, thank you for looking into it. 

kev.
