### ISSUE TITLE
Missing scan list and port list - possible solution

### ISSUE THREAD

**Issue by xjobex** [yu210148/gvm_install#27]
Hi, I installed GVM 20 on Ubuntu 20 using your script, but in my installation I noticed that 'scan configs' and 'port lists' were empty, and I was unable to start a scan task.
Searching in the logs and in this community thread https://community.greenbone.net/t/no-scan-list-no-port-lists-after-build-of-20-08/6360/9 I found a solution that is working for me:

```
mkdir -p /opt/gvm/var/lib/gvm/data-objects/gvmd
rsync -avrP rsync://feed.community.greenbone.net:/data-objects/gvmd/ /opt/gvm/var/lib/gvm/data-objects/gvmd/
chown -R gvm:gvm /opt/gvm/var/lib/gvm/
reboot
```

**Comment by yu210148** [comment]
Hi there,

Yes, it seems to be a timing issue with the initial feed updates. It can happen with the other feeds too from what I've found and have added the following to the README that addresses it:

> Seems, that after completing the script for version 20 the machine needs to be restarted. Then you should be able to log into the web interface. Once logged in, head over to Administration-->Feed Status. If any of the feeds show a status of 'Update in progress' wait until they're completed. While you're waiting, log in to a command prompt on the machine and become the GVM user (e.g., sudo -i, su gvm). List the gvm user's crontab file with 'crontab -l' and manually execute the commands shown there (e.g., '/opt/gvm/sbin/greenbone-feed-sync --type SCAP') once the feed status changes from 'Update in progress' to the feed's actual status. When you run the commands from the crontab the feed status update as shown in the web interface will change back to show that it's updating. Again, wait for it to complete before running the next line from the crontab. Once all the feeds are showing versions that look like dates (e.g., 20201229T1131) and the status is no longer showing as updating you should be able to start a scan using the OpenVAS Scanner under Scans-->Tasks-->New Task.

kev.
