### ISSUE TITLE
Script for Debian 10

### ISSUE THREAD

**Issue by ManuelFFF** [yu210148/gvm_install#3]
Hi, 

Do you have plans or could create something similar for Debian 10? Or maybe the same script will work? The following link is an excellent source you could use:

https://sadsloth.net/post/install-gvm11-src-on-debian/

Thanks

**Comment by yu210148** [comment]
Hi Manuel,

I'm sure it could be adapted for Debian 10. I'm not sure what--if any--changes would be needed. If I get a chance I may take a look at adapting it to Debian but I don't have any plans to at the moment. Typically, I run GVM in a VM and it's just as easy to use Ubuntu as it is Debian; although I do use Debian as my base OS for the VMs. If you--or anyone else--want's to fork this for Debian (or CentOS, Arch, Gentoo, etc.) I'd be happy to have a look at that.

kev.
