### ISSUE TITLE
Not being able to login?

### ISSUE THREAD

**Issue by chrispdejonge** [yu210148/gvm_install#30]
Hi,

I can't seem to get a login to work with this script. I've tried the waiting, cron job, restarting of the system. Sadly, nothing works and i keep getting a "**Login Failed. Invalid password or username.**" message on the web UI. Any idea why this would be the case? Using ubuntu 20.04 and version 20 for gvm. Tried reinstalling and reconfiguring the machine, but nothing seems to work.

**Comment by yu210148** [comment]
Humm, not sure why that would be. What's the username you're trying to log
in with? I haven't run this in a while so perhaps something changed on the
gvm side when I wasn't looking.

Kev.

**Comment by chrispdejonge** [comment]
Hi,

I am trying to log in with user gvmadmin and password StrongPass as documented in the script

Op 8 mrt. 2021 23:05 schreef Kevin Lucas <notifications@github.com>:

Humm, not sure why that would be. What's the username you're trying to log
in with? I haven't run this in a while so perhaps something changed on the
gvm side when I wasn't looking.

Kev.

**Comment by yu210148** [comment]
Okay, let me re-run it on a 20.04 machine and see if I can replicate and troubleshoot this.

kev.

**Comment by yu210148** [comment]
Humm, I'm afraid I've been unable to replicate the issue. Once the script completed I was able to log in to the web interface and update the system with the default username and password using an Ubuntu 20.04 server system on a KVM host. 

The relevant line is 404 in the script. You could try executing `/opt/gvm/sbin/gvmd --create-user gvmadmin --password=StrongPass` as the gvm user and create whatever username/password you'd like and see if that'd do the trick. I usually get to the gvm user by doing `sudo -i` then `su gvm`. 

I'm not sure why it isn't working for you as is though. Perhaps someone else who sees this has an idea?

kev.

**Comment by yu210148** [comment]
I'm going to close this off for now but we can reopen it again in the future if needed.
