### ISSUE TITLE
Problem creating a Scan Config

### ISSUE THREAD

**Issue by Rdago** [yu210148/gvm_install#38]
Hi There! 

thanks for your Install script. 
I was trying to install GVM for the last 2 days but I always got this error: 

```
Failed to find config 'daba56c8-73ec-11df-a475-002264764cea'
```

no matter which Distro I tried (Ubuntu 20.04 Server, Kali 2020.1, newest Kali, Debian) I always get the same issue above when I try to run scans. 

Some Logs I got: 

```
ospd-openvasd.log: 

OSPD[41878] 2021-04-22 07:52:54,014: ERROR: (ospd.server) Error sending data to the client. [Errno 32] Broken pipe
OSPD[41878] 2021-04-22 07:52:54,344: INFO: (ospd.main) Shutting-down server ...
OSPD[1159] 2021-04-22 07:53:52,905: INFO: (ospd.main) Starting OSPd OpenVAS version 20.8.3.dev1.
OSPD[1159] 2021-04-22 07:56:59,111: ERROR: (ospd_openvas.openvas) OpenVAS Scanner failed to load VTs. Command '['openvas', '--update-vt-info']' died with <Signals.SIGABRT: 6>.


gvmd.log:

event config:MESSAGE:2021-04-22 08h22.20 UTC:14332: Config could not be created by gvmadmin
event config:MESSAGE:2021-04-22 08h22.22 UTC:14343: Config could not be created by gvmadmin
event config:MESSAGE:2021-04-22 08h22.22 UTC:14348: Config could not be created by gvmadmin


```

Isn´t it possible to provide a .OVA file in order to easy deploy?

**Comment by yu210148** [comment]
Hi there, 

Humm, not sure why that would be. I'm troubleshooting another issue with the feeds  #36 that may be related. 

I don't have an .OVA because I'm using KVM rather than VirtualBox for testing. I could clean one up and provide the .qcow2 file if you have somewhere I could upload it?

kev.

**Comment by Rdago** [comment]
Hi @yu210148 

got it running now  - don´t ask me how I just ran every freaking command I was finding in Forum and Github pages where people say "you just need to update your data" -> NO DEFINITLY NOT. 

Did a lot of things and somehow it works now. 

Would still love to see a clean installation of it for further using. 

Maybe you can `dd` the whole system into a bootable iso file or something like this? 

If there is a possibility I would provide you an upload Link via DM. 

Thanks
@Rdago

**Comment by yu210148** [comment]
Hi again,

Of course, as I'm playing around testing these issues I find that they've
released a new version as of a few days ago. I should stop cloning their
GitHub branches and start using their release files so things don't change
underneath what the script is doing.

When I get a chance I'll see what I can do.

Kev.

**Comment by Jarli01** [comment]
Thanks @yu210148

**Comment by yu210148** [comment]
Hi Rdago,

I converted one of the GVM20 virtual machines into an .OVA for you if you'd still like one. Just let me know where you'd like a 3GB file uploaded to :)

kev.

**Comment by Rdago** [comment]
thanks for your help @yu210148 your .OVA works perfectly!
