### ISSUE TITLE
Use tag instead of branch

### ISSUE THREAD

**Issue by equinoxefr** [yu210148/gvm_install#39]
Hi, a little suggestion,

Instead of using branch to clone the repositories, you can use tags to get a specific and "stable" version.

For example: `sudo -Hiu gvm git clone -b v21.4.0 https://github.com/greenbone/gvm-libs.git`

Many thanks for your script, it's perfect.

Best regards

**Comment by yu210148** [comment]
Thanks, I was looking for something like this. I'll add it in.

kev.
