### ISSUE TITLE
missing lines

### ISSUE THREAD

**Issue by copenhaus** [yu210148/gvm_install#4]
Hi.

I think you are missing some commands/lines:
line 34 (after "systemctl restart postgresql"), missing "systemctl enable postgresql"
line 69 (in "openvas" section, after "cmake"), missing two lines:
		sudo -Hiu gvm echo "make" | sudo -Hiu gvm tee -a /opt/gvm/.bashrc
		sudo -Hiu gvm echo "make install" | sudo -Hiu gvm tee -a /opt/gvm/.bashrc

Also, since this is a brand new install, I am not sure "touch .bashrc", then "mv .bashrc .bashrc.bak", execute, rm ".bashrc" then "mv .bashrc.bak .bashrc" steps are necessary, as ".bashrc" is surely empty.

Again, since this is a new install/creation, the "export PKG_CONFIG_PATH" don't need to include $PKG_CONFIG_PATH (as it's an empty string)

Just my 2p.

Thanks....

**Comment by yu210148** [comment]
Thanks, I've added the lines. I realize there may be redundant things in there but I figured '...better safe than sorry.' so I've left them in. :)

**Comment by copenhaus** [comment]
Now this script works great!

I also *humbly* want to make a suggestion:  right at the end of the script, where you create 'grvadmin' user, if it would simply prompt for a password, that would be awesome!

**Comment by copenhaus** [comment]
I am still, however, stuck on the Task report telling me "Invalid date" for "Duration of last scan" upon my first scan... :(
