### ISSUE TITLE
Question - Scan Configs

### ISSUE THREAD

**Issue by Jarli01** [yu210148/gvm_install#46]
Regarding the scan configs which get included by default, at there any other that you @yu210148 import by default?

If so what are they, and do you have a trusted source to get additional configs from?

**Comment by yu210148** [comment]
Hi again,

There aren't any beyond what's included in the GVM_DATA feed that I typically use. If you haven't already, it might be worth asking over at https://community.greenbone.net/ I'm not sure how much trust to put into configs found through the forum though.

kev.

**Comment by Jarli01** [comment]
Yeah I hadn't gone into the community forums to delve for that info. 

Okay no problem, well closing this on as it seems the defaults are good enough.
