### ISSUE TITLE
Please help on listening address.

### ISSUE THREAD

**Issue by JaseNZC** [yu210148/gvm_install#50]
This installs well on a fresh install on ubuntu 20.04 and I can run it from the local machine fine.

What do I need to change so I can access it from a remote machine on the same network ??

**Comment by JaseNZC** [comment]
My fault, all sorted.

**Comment by yu210148** [comment]
Glad to hear you got it sorted out 🙂

Kev.

**Comment by rybli** [comment]
> My fault, all sorted.

If you can remember, can you post what the issue was and how it was solved?
