### ISSUE TITLE
issue on scanning? 

### ISSUE THREAD

**Issue by killmasta93** [yu210148/gvm_install#51]
Hi
Currently installed GVM 21 on ubuntu 18.04 
i checked that the databases are updated but it shows on the scan N/A any idas?
im testing the scan to a windows 7 which purposely has many vulnerabilities which should show on high  

Thank you 

![image](https://user-images.githubusercontent.com/13953629/126402967-b9629c72-f74b-4d03-8b2c-d9727f8683f1.png)

![image](https://user-images.githubusercontent.com/13953629/126403031-fd9d5871-1648-4497-a693-4b8d194b66ca.png)
![image](https://user-images.githubusercontent.com/13953629/126403078-0ddcd1c7-cc36-4adf-865c-a37f3041e455.png)

**Comment by popokoko** [comment]
ping 192.168.3.37

**Comment by killmasta93** [comment]
it seems that i have to run https://github.com/yu210148/gvm_install/issues/48 before to make it work

**Comment by killmasta93** [comment]
it seems if i cant ping it wont scan?

**Comment by rybli** [comment]
@killmasta93 if you're still looking for an answer, take a look at Issue #76 and see if that gets you what you want.
