### ISSUE TITLE
This report exceeds the maximum length of 1048576 characters and thus was truncated.

### ISSUE THREAD

**Issue by impact1560** [yu210148/gvm_install#52]
Hello,

I love the script... I'm having just this one problem with sending the PDF reports. I get an error message "This report exceeds the maximum length of 1048576 characters and thus was truncated." I searched online and tried a couple of things to fix, but nothing is working. Can you please help?

**Comment by yu210148** [comment]
Hi There, 

I'm not sure this is an issue with the installer. I haven't run into it before so it might be better to open an issue with the component that generates them. I'm not affiliated with the Greenbone or OpenVAS project itself and I'm not sure which component is the one that makes the PDF output but if I had to guess I'd start with the gsa project at https://github.com/greenbone.

If I'm wrong and it is some installer flag I'd be happy to include it but I'm not sure what that would be.

kev.

**Comment by impact1560** [comment]
The PDF output works fine but when sending the PDF in an email that's different. You are correct this has nothing to do with the installer.

**Comment by yu210148** [comment]
Sorry I couldn't have been of more help.

kev.
