### ISSUE TITLE
No login via smb while scanning

### ISSUE THREAD

**Issue by jgrete** [yu210148/gvm_install#58]
Hello,
I've used this wonderful script for the first time on a Ubuntu 20.04.3 VM and as far as I could see it went well and created a working  GSA version  21.04. I was able to create tasks and scanned linux machines. I did not manage to get the openvas-smb working it seems. The scanning process did not even try to login to  windows machines (ssh on linux works well). The resulting reports do not contain a "smb"-row in the "Host Authentication" table, so I suspect the openvas-smb is not active/loaded/linked (no idea how to verify that). The build process did not show any errors or warnings regarding openvas-smb (I will rerun it and try to capture the output to be sure).
Any ideas?
Kind Regards
Juergen

**Comment by yu210148** [comment]
Hi Juergen,

Humm, no, not sure what's going on there. Unfortunately, I don't have any windows machines that I can use to investigate this. If anyone else reading this has any ideas what might be the issue here please let me know.

kev.

**Comment by jgrete** [comment]
Hi Kevin,
you do not need to have a windows machine. Just fill out the smb credentials in the target window and scan a machine. The resulting report should contain a smb row in the chapter "1.1 Host Authentications". You'll get a "failure" of course, but the fact that you've gotten a smb-row proves that opnvas-smb is in use. 
With my  20.08 GSA I'm gewtting such a row, using your script there's no row.
I have to try the manual method now - deadlines ...

**Comment by rybli** [comment]
Just coming back to some of these open issues. This seems to be the same issue I was experiencing with Issue #76.

**Comment by rybli** [comment]
@jgrete if you're still in need take a look at the link in that issue and see if the fix does what you want.

**Comment by jgrete** [comment]
@rybli in the meantime i am retired so I'm not really in need :-)
I remember that we did an update to the latest version and as a side effect the problem vanished.
So, I think this issue should be closed.
