### ISSUE TITLE
New install on Ubuntu 20.04.3 not starting

### ISSUE THREAD

**Issue by XaeroTheHero** [yu210148/gvm_install#66]
Just did a clean install of Ubuntu 20.04.3 with nothing installed other than openSSH. I ran the suggested default install commands:

wget https://raw.githubusercontent.com/yu210148/gvm_install/master/install_gvm.sh
chmod +x install_gvm.sh
sudo ./install_gvm.sh -v 21 -u

Install seems to finish successfully, but no GUI or service responds on https://xxx.xxx.xxx.xxx
I rebooted the server, still nothing.

The user I made before running the install script now has this in his home folder:

root@gvmsource:/home/gvm# ls -al
total 5748
drwxr-xr-x 11 gvm  gvm     4096 Dec 22 07:15 .
drwxr-xr-x  3 root root    4096 Dec 22 07:03 ..
-rw-------  1 gvm  gvm      203 Dec 22 07:15 .bash_history
-rw-r--r--  1 gvm  gvm      220 Feb 25  2020 .bash_logout
-rw-r--r--  1 gvm  gvm     3771 Feb 25  2020 .bashrc
drwx------  2 gvm  gvm     4096 Dec 22 07:07 .cache
drwxrwxr-x  7 gvm  gvm     4096 Oct 12 12:16 gsa-21.4.3
-rw-rw-r--  1 gvm  gvm  2683994 Dec 22 07:13 gsa-21.4.3.tar.gz
drwxrwxr-x  9 gvm  gvm     4096 Oct 12 06:59 gvmd-21.4.4
-rw-rw-r--  1 gvm  gvm  1031202 Dec 22 07:13 gvmd-21.4.4.tar.gz
drwxrwxr-x 11 gvm  gvm     4096 Oct 11 14:38 gvm-libs-21.4.3
-rw-rw-r--  1 gvm  gvm   297761 Dec 22 07:13 gvm-libs-21.4.3.tar.gz
-rwxrwxr-x  1 gvm  gvm    32069 Dec 22 07:10 install_gvm.sh
drwxr-xr-x  2 root root    4096 Dec 22 07:12 node_modules
drwxrwxr-x 12 gvm  gvm     4096 Oct 11 15:37 openvas-scanner-21.4.3
-rw-rw-r--  1 gvm  gvm   454482 Dec 22 07:13 openvas-scanner-21.4.3.tar.gz
drwxrwxr-x  8 gvm  gvm     4096 Apr 15  2021 openvas-smb-21.4.0
-rw-rw-r--  1 gvm  gvm  1082191 Dec 22 07:13 openvas-smb-21.4.0.tar.gz
drwxrwxr-x  6 gvm  gvm     4096 Oct 12 13:50 ospd-21.4.4
-rw-rw-r--  1 gvm  gvm   127090 Dec 22 07:13 ospd-21.4.4.tar.gz
drwxrwxr-x  7 gvm  gvm     4096 Oct 12 12:05 ospd-openvas-21.4.3
-rw-rw-r--  1 gvm  gvm    91272 Dec 22 07:13 ospd-openvas-21.4.3.tar.gz
-rw-r--r--  1 gvm  gvm      807 Feb 25  2020 .profile
-rw-r--r--  1 gvm  gvm        0 Dec 22 07:07 .sudo_as_admin_successful
-rw-rw-r--  1 gvm  gvm      180 Dec 22 07:10 .wget-hsts
-rw-r--r--  1 root root      86 Dec 22 07:12 yarn.lock

Advice please?

**Comment by XaeroTheHero** [comment]
Okay, so I started over from the beginning with a new clean install VM. It seems that if you already have created the user "gvm", the install breaks somewhere along the way, without any real errors. When I made this new VM I had created another username, and now installation process looks totally different.

**Comment by yu210148** [comment]
Huh, never really considered that one might create the 'gvm' user before starting. The script tries to create it while it's running. I'm not surprised things broke along the way. I guess should be added to the known issues. :)

kev.
