### ISSUE TITLE
New GVM 21 install on Debian 10.11 has no scanner config

### ISSUE THREAD

**Issue by XaeroTheHero** [yu210148/gvm_install#67]
In trying to get this to work, I did a clean install of Debian 10.11, then ran suggested default installation:

apt install sudo
usermod -aG sudo <your-user-name> # add your user to the sudoer's group
wget https://raw.githubusercontent.com/yu210148/gvm_install/master/install_gvm.sh
chmod +x install_gvm.sh
sudo -i
./install_gvm.sh

Install completed fine, feed updated fine and GUI works fine. When trying to start a new scan, there's no default scanner config available, and in place there's a random string (See below image link). When trying to add a new scanner config, exception is thrown with message that "said random string" could not be updated.

https://imgur.com/oVjfdt4

Which linux dist and version does this script work with out of the box? Ubuntu 20.04.3 with GVM 21 did not work either, reports are just empty, even after trying the suggested manual fix in regards to NMAP.

**Comment by yu210148** [comment]
Humm, last time I ran it on 20.04 it worked okay. I'll have to check into
this. Not sure what would be causing that. I have a newborn though, she her
grandmother arrives for the first time seeing her later today so I'm not
sure when I'll have a chance. If anyone else seeing this has any ideas
please let us know.

**Comment by XaeroTheHero** [comment]
I am not sure what happened here exactly, but when I re-ran feed update manually according to below, it now has all the default scanner configs.

c) /opt/gvm/sbin/greenbone-feed-sync --type SCAP
d) /opt/gvm/bin/greenbone-nvt-sync
e) /opt/gvm/sbin/greenbone-feed-sync --type CERT
f) /opt/gvm/sbin/greenbone-feed-sync --type GVMD_DATA
g) /usr/bin/sudo /opt/gvm/sbin/openvas --update-vt-info
