### ISSUE TITLE
Report outdated / end-of-life Scan Engine / Environment (local)

### ISSUE THREAD

**Issue by elyeschemengui** [yu210148/gvm_install#71]
A severity with 10 has been reported in every scan as it detects end of life scan engine.

Fix: need to update to latest version of openvas-scanner: 21.4.4

the script of update is it still on test phase ?

**Comment by yu210148** [comment]
Should be fixed now although it does need a fresh install. See <a href=https://github.com/yu210148/gvm_install/issues/69>Issue #69</a> for more info.
