### ISSUE TITLE
GVMD_DATA not updating. 

### ISSUE THREAD

**Issue by marchwicki** [yu210148/gvm_install#72]
I'm getting "Too old (68 days) Please check the automatic synchronization of your system" for the the GVMD_DATA. I thought it was them not updating it but on a different install it's updating. Any ideas how I can update or troubleshoot this? Apologies I don't have more information for you. I'm kind of a noob with this product and am not sure where to look to troubleshoot.

**Comment by marchwicki** [comment]
The GUI is saying my GVMD_DATA version is 20220128T1556

**Comment by yu210148** [comment]
Humm, I have the same thing and also thought it was just something that
didn't change all that often on their end. I'll check into it when I get a
chance.

Kev.

**Comment by marchwicki** [comment]
Same install and update scripts for your repo.

**Comment by yu210148** [comment]
Okay, cool. Very odd indeed; two instances, same script one good, one not.

The thing uses the random number generator to set up the cron jobs that do
the updates so perhaps they're clobbering eachother on our non working
setups. I'll have a look at mine when I get a sec. Could you post the
crontab of the gvm user for your non working one vs the working one and we
can compare?

Kev.

**Comment by yu210148** [comment]
Here's mine: 

> gvm@gvm21:~$ crontab -l
50 21 * * * /opt/gvm/sbin/greenbone-feed-sync --type SCAP
51 14 * * * /opt/gvm/bin/greenbone-nvt-sync
3 4 * * * /opt/gvm/sbin/greenbone-feed-sync --type CERT
47 0 * * * /opt/gvm/sbin/greenbone-feed-sync --type GVMD_DATA
44 8 * * * /usr/bin/sudo /opt/gvm/sbin/openvas --update-vt-info

It doesn't look like it should be getting clobbered by any of the other jobs so there may be something else going on.

**Comment by yu210148** [comment]
Just so I've got this written down somewhere here's the output I'm getting when I run the update manually:

> gvm@gvm21:~$ /opt/gvm/sbin/greenbone-feed-sync --type GVMD_DATA
> Greenbone community feed server - http://feed.community.greenbone.net/
> This service is hosted by Greenbone Networks - http://www.greenbone.net/
> 
> All transactions are logged.
> 
> If you have any questions, please use the Greenbone community portal. 
> See https://community.greenbone.net for details.
> 
> By using this service you agree to our terms and conditions.
> 
> Only one sync per time, otherwise the source ip will be temporarily blocked.
> 
> receiving incremental file list
> timestamp
>              13 100%   12.70kB/s    0:00:00 (xfr#1, to-chk=0/1)
> 
> sent 43 bytes  received 108 bytes  60.40 bytes/sec
> total size is 13  speedup is 0.09

**Comment by yu210148** [comment]
Well, Here's <a href=https://community.greenbone.net/t/gvmd-data-not-updated/11755>someone else with this posting on the greenbone forms</a>. The accepted answer there is that the feed isn't updated that often. What's the version of the GVMD_DATA on the one that's working for you?

kev.

**Comment by yu210148** [comment]
Kept digging and found that one of the moderators of the greenbone forum confirms that 202201281556 was the current feed version as of March 1st:

https://community.greenbone.net/t/gvmd-data-too-old-34-days-please-check-the-automatic-synchronization-of-your-system/7565/21

**Comment by marchwicki** [comment]
My second instance must have something else going on with it. In the GUI it was showing a different feed version but also said it was up to date after I ran the 5 feed syncs . I ran your update_gvm.sh script from the repo and now it's showing the same thing as my home instance. My second instance is in a more locked down environment and I am only able to hit the GUI on an old Windows Server VM with an outdated IE browser. I wonder if it was something as simple as a browser cache issue.

**Comment by yu210148** [comment]
Humm, I'm not sure either. The update script isn't something I've touched in a long time and it doesn't do anything useful yet. It's more just there as a reminder that it's something the project could use at some point in the future.

I'm going to close this off for now; it sounds like you've got it working as expected. We can reopen it later if we need to.

**Comment by vrracerx** [comment]
is there no way to do a mock update so that this error clears on a monthly basis? it just bugs me that this looks broken 95% of the time

**Comment by yu210148** [comment]
Not from my end that I'm aware of. As far as I know it would have to come
from Greenbone in their community feed.

Kev.
