### ISSUE TITLE
What's the recommended way to update versions? 

### ISSUE THREAD

**Issue by marchwicki** [yu210148/gvm_install#77]
I'm trying to update to version 21.4.4 from version 21.4.3. What is the best way to do this with your setup?

**Comment by yu210148** [comment]
I usually just install a new instance on a fresh Ubuntu. I haven't written a script to do an in-place upgrade although I admit it would be a good thing to do.

**Comment by marchwicki** [comment]
Thanks for the quick response Kevin! That's what I ended up doing. Do you manually rebuild all your targets, creds, tasks... each time or do you back everything up and import the old settings somehow? I couldn't find anything in the GUI to export the configuration.

**Comment by yu210148** [comment]
Personally, I do a clean Ubuntu install and install the new version with
the script. I don't have a way to update in place. It's not ideal I know
but I haven't had a chance to figure out how to do an in place upgrade.

Kev.
