### ISSUE TITLE
Incorrect variable name results version update fail.

### ISSUE THREAD

**Issue by itiligent** [yu210148/gvm_install#80]
Hi, and thanks for your great work!

see line 218:  sudo  -Hiu gvm echo "cd /opt/gvm/gvm-libs-$GVM_VERSION" | sudo -Hiu gvm tee -a /opt/gvm/.bashrc

This line is a bit of an outlier in that is the only one in the pattern callig the wrong variable name. $GVM_VERSION above should be $GVM_LIBS_VERSION. 

When using the script on 21.4.4 it still works due to the phasing of previous version numbers. 

I found this when adapting the script to install 21.4.5. The only other changes to install 21.4.5 seem to be:

    export GVM_VERSION=21.4.5
    export GVM_LIBS_VERSION=21.4.4
    export GVMD_VERSION=21.4.5
    export GSA_VERSION=21.4.4
    export OPENVAS_SMB_VERSION=21.4.0
    export OPENVAS_SCANNER_VERSION=21.4.4
    export OSPD_VERSION=21.4.4
    export OSPD_OPENVAS_VERSION=21.4.4
    export GSAD_VERSION=21.4.4

**Comment by yu210148** [comment]
Thanks for the info I'll have a look next time I'm in front of my computer.

Kev.

**Comment by yu210148** [comment]
Thanks again, just committed the change on line 218.

kev.
