### ISSUE TITLE
missing "su gvm -c"  at start of vt update command 

### ISSUE THREAD

**Issue by itiligent** [yu210148/gvm_install#84]
Hi,
I just noticed on line 626 there seems to be a little error on one of the database update commands:

    /opt/gvm/sbin/openvas --update-vt-info

I assume it should be: 

su gvm -c "/opt/gvm/sbin/openvas --update-vt-info"

**Comment by yu210148** [comment]
Thanks, I'll take a look when I can.

Kev.

**Comment by yu210148** [comment]
Cool, kiddo is being a handful today. If you have a chance to put the
changes into a pull request I could merge it from my phone otherwise it'll
have to wait until I get time in front of my screen to do it.

Kev.
