### ISSUE TITLE
missing dependency to build credential exe files

### ISSUE THREAD

**Issue by itiligent** [yu210148/gvm_install#89]
Hi,

There is a dependecy on the package "nsis" for creating the credetial scan .exe packages.

Without this the package does not build and results in a zero byte file downloaded from the console.

After installing nsis, the exe pacackge builds and works correctly (tested on windows 2019 domain controller)

**Comment by yu210148** [comment]
Cool, thanks for this. I've added nsis in as one of the packages that the script installs.

kev.
