### ISSUE TITLE
GMP Service is down

### ISSUE THREAD

**Issue by Mangolinux** [yu210148/gvm_install#9]
used your script and when I try to login I get GMP Service is down

**Comment by aretsmarvin** [comment]
I have the same issue. Someone who could help us?

**Comment by aretsmarvin** [comment]
https://github.com/yu210148/gvm_install/issues/8

I think you need to wait. After a while it works. It possible busy with some updates.

**Comment by yu210148** [comment]
I admit I don't have a clue why it does this but when I just fired up my Ubuntu and Debian VMs to look into this they both no longer have the issue. My guess is that it's some sort of timing issue. 

If anyone else can figure it out or has any ideas I'm all ears. 

kev.

**Comment by yu210148** [comment]
I'm going to close this off for now but we can re-open it in the future if needed.
