### ISSUE TITLE
Error in line 98 "else"

### ISSUE THREAD

**Issue by jeremias-mazzeo** [yu210148/gvm_install#97]
ubuntu@ip-172-29-4-144:~$ sudo ./install_gvm.sh -v 21 -u
./install_gvm.sh: line 98: syntax error near unexpected token `else'
./install_gvm.sh: line 98: `else '

Ubuntu 22.04 LTS

**Comment by adamz01h** [comment]
`if [[ $GVMVERSION = "22" ]] || [[ $GVMVERSION = "21" ]] || [[ $GVMVERSION = "20" ]]; then
    if [[ $GVMVERSION = "22" ]]; then
        echo "Version 22 isn't working yet"
        echo "see (https://github.com/yu210148/gvm_install/issues/95) for more info"
        exit
    else
        echo "Okay, installing version $GVMVERSION"
    fi
else 
    echo "Sorry, I didn't understand the input $GVMVERSION."
    echo "Please re-run install_gvm.sh and enter a version number at the prompt"
    exit 1
fi`

add the fi after `  echo "Okay, installing version $GVMVERSION"` to close the if/then/else block in bash

**Comment by yu210148** [comment]
Oops, sorry about that. Just merged a fix a7ea929
