### ISSUE TITLE
Here's a link to newest GVM source build & docker build scripts.. 

### ISSUE THREAD

**Issue by itiligent** [yu210148/gvm_install#99]
The script  in this repo has over time deviated a fair bit form the current GVM build requirements & dependency needs. The structure makes determining whats needed for an upgrade a little harder too. You are likely to have many issues tring to work with it now. Its done a great job, but Greenbone kept moving the goalposts a little while back. 

Here's  some new build scripts (July 2023) for both a source built and Docker built GVM appliance. 

Both builds follow Greenbone's current documentation and stated dependencies, and both also add an industry standard Nginx reverse proxy with self signed SSL (rather than deal ith Greenbones awkward SSL approach.) For the Docker build, Greenbone's official community containers are used.
[https://github.com/itiligent/GVM-Install](https://github.com/itiligent/GVM-Install) 

Tested ok with windows credential scans on Debian 11 & 21 , Ubuntu 22.x &  Raspian Bullseye.

**Comment by yu210148** [comment]
Thanks for this. I've added a note in the read me with a link to your installer. This version is now end-of-life.
